---
- name: VPN | Configuration | Copy easy-rsa scripts
  command: "rsync -avi /usr/share/easy-rsa /etc/openvpn"
  args:
    creates: /etc/openvpn/easy-rsa/easyrsa

- name: VPN | Configuration | Create link to openssl config
  file:
    src: /etc/openvpn/easy-rsa/openssl-easyrsa.cnf
    dest: /etc/openvpn/easy-rsa/openssl.cnf
    state: link

- name: VPN | Configuration | Create easy-rsa vars
  template:
    src: easy_rsa_vars.focal
    dest: /etc/openvpn/easy-rsa/vars

- name: VPN | Configuration | Copy easy-rsa vars to config directory
  copy:
    src: /etc/openvpn/easy-rsa/vars
    dest: /etc/openvpn/config/easy-rsa.vars
    remote_src: true
    mode: 0644

- name: VPN | Configuration | Create sym-link for pki
  file: 
    src: /etc/openvpn/easy-rsa/pki
    dest: /etc/openvpn/pki
    state: link
